### ISSUE TITLE
Addon stop import movies

### ISSUE THREAD

**Issue by privat-allin** [primaeval/plugin.video.imdb.watchlists#3]
Hi, 
 the addon stoped import new content from imdb, i think imdb changed somthing.
Ty

**Comment by primaeval** [comment]
What type of a list is it and have you got it set to public? I think they changed the default privacy setting recently. My normal list worked just now for me.

**Comment by privat-allin** [comment]
hi
the list was working great for a year
just two weeks ago it stopeed
the list is public you can see it
http://www.imdb.com/user/ur48749440/lists?ref_=nv_usr_lst_3
http://www.imdb.com/list/ls068584810/

the problem is in all my devices android and windows

if it help i copy the error from kodi log

 Error Type: <type 'exceptions.IOError'>
                                            Error Contents: (2, 'No such file or directory', 'C:\\Users\\user\\AppData\\Roaming\\Kodi\\userdata\\addon_data\\plugin.video.imdb.watchlists\\.storage\\library_watchlists.tmp')
                                            Traceback (most recent call last):
                                              File "C:\Users\user\AppData\Roaming\Kodi\addons\plugin.video.imdb.watchlists\main.py", line 919, in <module>
                                                plugin.run()
                                              File "C:\Users\user\AppData\Roaming\Kodi\addons\script.module.xbmcswift2\lib\xbmcswift2\plugin.py", line 339, in run
                                                storage.close()
                                              File "C:\Users\user\AppData\Roaming\Kodi\addons\script.module.xbmcswift2\lib\xbmcswift2\storage.py", line 69, in close
                                                self.sync()
                                              File "C:\Users\user\AppData\Roaming\Kodi\addons\script.module.xbmcswift2\lib\xbmcswift2\storage.py", line 63, in sync
                                                shutil.move(tempname, self.filename)    # atomic commit
                                              File "E:\programs\Kodi17\system\python\Lib\shutil.py", line 302, in move
                                                copy2(src, real_dst)
                                              File "E:\programs\Kodi17\system\python\Lib\shutil.py", line 130, in copy2
                                                copyfile(src, dst)
                                              File "E:\programs\Kodi17\system\python\Lib\shutil.py", line 82, in copyfile
                                                with open(src, 'rb') as fsrc:
                                            IOError: (2, 'No such file or directory', 'C:\\Users\\user\\AppData\\Roaming\\Kodi\\userdata\\addon_data\\plugin.video.imdb.watchlists\\.storage\\library_watchlists.tmp')
                                            -->End of Python script error report<--

**Comment by primaeval** [comment]
They've changed a lot of the html. I'll see if I can fix it sometime this week.

**Comment by privat-allin** [comment]
Okay mate, ty very much.

**Comment by primaeval** [comment]
The ur list is not public

> This list is not public
> The creator of this list has not enabled public viewing

I've done some fixes for the ls list. Try installing the latest commit version. If it works I'll tidy it up and release it. You can just copy the main.py file over the one you have now to test it.

**Comment by privat-allin** [comment]
Okay mate it looks great now, it start scraping again, i will update you if i see any problems, lot of thanks

**Comment by primaeval** [comment]
ur and ls lists?

**Comment by privat-allin** [comment]
I use just ls lists so i dont know if ur also work

**Comment by primaeval** [comment]
It's out as 0.0.37. I haven't fixed things like plot and genre but at least you can play your movie lists now.

**Comment by privat-allin** [comment]
Ty, i use it only from librery so its okay for me like this.
